name: PYTHON APPLICATION
on:
  workflow_dispatch
jobs:
  unit-test:
    name: Running unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application code
        uses: actions/checkout@v7
      - name: verify files
        run: | 
          pwd
          ls -al
          ls
      - name: set-up python
        uses: actions/setup-python@v7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit test
        run: pytest -v app.py


