name: TESTING CHECKOUT #set name for the workflow
on: push #set the trigger to push
jobs: #Job declaration
  job1: #first job ID
    name: JOB1 #name of first job
    runs-on: ubuntu-22.04 #Set the machine environment to ubuntu-22.04
    steps: #declare set of commands to run sequencially
      - name: step 1 #name of first step 
        run: | #commands to run in step one
          echo "Good Evening DevOps" 
          pwd 
          hostname
          ls -la
      - name: step 2 #name of second step
        uses: actions/checkout@v5 #uses checkout to pull necessary file from working repository
      - name: Step 3  #name of third step
        run: | #command to run in step three
          mkdir demo
          pwd >> demo/test.txt #redirecting output into a file test.txt for uploading
          hostname >> test.txt
          echo "I am a mathematician, i love coding" >> demo/hubby.txt
          ls -la >> demo/list.txt
          echo "today's date is $(date +%F)" >> demo/date.txt
          echo "Let's make it right again" >> motivate.txt
      - name: step 4
        uses: actions/upload-artifact@v7
        with:
          name: single_file
          path: |
            ./test.txt
            ./motivate.txt
      - name: step 5
        uses: actions/upload-artifact@v7
        with:
          name: Directory_artifact
          path: |
            demo/list.txt
            demo/hubby.txt
            demo/date.txt
    
  job2: #first job ID
    name: JOB2 #name of first job
    needs: job1
    runs-on: ubuntu-22.04 #Set the machine environment to ubuntu-22.04
    steps: #declare set of commands to run sequencially
      - name: checking current directory
        run: |
          pwd
          ls -ltr
      - name: downloading single file artifacts
        uses: actions/download-artifact@v7
        with:
          name: single_file
      - name: checking current directory to confirm the existing of single_file
        run: |
          pwd
          ls -ltr
  job3: #third job ID
      name: JOB3 #name of third job
      needs: job1
      runs-on: ubuntu-22.04 #Set the machine environment to ubuntu-22.04
      steps: #declare set of commands to run sequencially
        - name: checking current directory
          run: |
            pwd
            ls -ltr
        - name: downloading directory artifacts
          uses: actions/download-artifact@v7
          with:
            name: Directory_artifact
        - name: checking current directory to confirm the existing of downloaded directory artifacts
          run: |
            pwd
            ls -ltr
            cat date.txt
