name: CI
#Get trigger whenever changes is commited
on: push
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Run Bash Script
        run: echo "Goodevening"
      - name: System Info
        run: uname -v
