name: CI
#Get trigger whenever changes is commited
on: push
jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Run Bash Script
        run: echo "Goodevening"
      - name: System Info
        run: uname -v
      - name: create file
        run: |
          mkdir myfolder
          sleep 10
  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
      - name: Greeting message
        run: echo "Here's my first Actions"
      - name: running multiple commands
        run: |
          mkdir player
          pwd
          echo "Today's date is $(date)"
          sleep 5
