name: TESTING DEPLOYMENT
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  job1:
    name: Software to deployment stage
    runs-on: ubuntu-22.04
    steps:
        - name: Stage_1
          run: echo "Good Morning"
        - name: stage_2
          run: |
            touch file.txt
            echo "Today's date is $(date +%F)" >> file.txt
            echo "I am going to the School" >> file1.txt
        - name: uploading_artifacts
          uses: actions/upload-artifact@v7
          with:
            name: single_file
            path: |
                file.txt
                file1.txt 
  job2:
    name: testing
    runs-on: ububuntu-latest
    steps:
      - name: new
        run: |
          echo "Good Morning DevOps"
          pwd
  job3:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7
        
        
