name: TESTING DEPLOYMENT
on:
  pull_request:
    branches: [main]
jobs:
  job1:
    name: Software to deployment stage
    runs-on: ubuntu-22.04
    steps:
        - name: Stage 1
          run: echo "Good Morning"
  job2:
    name: testing
    runs-on: ububuntu-22.04
    steps:
      - name: new
        run: |
          echo "Good Morning DevOps"
          pwd
          
