name: GITHUB ACTION WORKFLOWS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  APP_NAME: Application
  APP_VERSION: 1.0
jobs:
  job1:
    name: uploading
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          mkdir demo
          echo "Username: ${{ secrets.USERNAME }}"
          echo "Password: ${{ secrets.PASSWORD }}"
          echo "APP_NAME: $APP_NAME" #reference and print the app name 
          echo "APP_VERSION: $APP_VERSION" #reference and print app version
          echo "Good morning DevOps Engineer!" >> greet.txt
          echo "i'm a Devops Engineer" >> demo/profile.txt
          echo "Hi! Good Evening Peers" >> greet.txt
          echo "i'm single and searching" >> demo/profile.txt
          echo "Have a nice day" >> demo.txt
      - name: Single_file_uploading
        uses: actions/upload-artifact@v7
        with:
          name: Single_file 
          path: |
            greet.txt
            demo.txt
      - name: directory_file_uploading
        uses: actions/upload-artifact@v7
        with:
          name: Directory_file
          path: |
            demo/
  job2:
    name: downloading
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: length_file (step 1)
        run: |
          ls 
      - name: download (step 2)
        uses: actions/download-artifact@v7
        with:
          name: Single_file
      - name: download (step 3)
        uses: actions/download-artifact@v7
        with:
          name:  Directory_file
      - name: Verify_files (step 3)
        run: |
          ls
          pwd
          echo "done"
  job3:
    name: Context Variables
    runs-on: ubuntu-latest
    steps:
      - name: Referencing Context Variables
        run: |
            echo "[INFO] Triggered by ${{ github.event_name }}"
            echo "[INFO] New changes were added by ${{ github.actor }} in ${{ github.ref_name }} branch"
            echo "[INFO] Current step by ${{ runner.os }}"
            echo "[INFO] Current JOB ID is ${{ job.check_run_id }}"
  deployment:
    name: Deploying Application
    runs-on: ubuntu-latest
    steps:
      - name: Refering Enviroments Variables
        run: echo "[INFO] Application is running on ${{ vars.HOST }} by User ${{ vars.USER}}"
      - name: Refering Enviroments Secrets 
        run: |
          echo "[INFO] Password for User ${{ vars.USERNAME }} is ${{ secrets.PASSWORD}}"
          echo "[INFO] the Database key is ${{ vars.DATABASE_KEY }}"
        environment:
          name: Deployment

  production:
    name: Production Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Refering Enviroments Variables
        run: echo "[INFO] Application is running on ${{ vars.HOST }} by User ${{ vars.USER}}"
      - name: Refering Enviroments Secrets 
        run: |
            echo "[INFO] Password for User ${{ vars.USER }} is ${{ secrets.PASSWORD}}"
            echo "[INFO] USER ${{ vars.USER }}" Host the website with ${{ vars.HOST}}
        environment:
          name: PRODUCTION
