name: LEARNING GITHUB ACTION
on: workflow_dispatch
jobs:
  job1:
    name: Run script
    runs-on: ubuntu-latest
    steps:
      - name: Echo greeting
        run: echo "Good Morning DevOps Engineers"
      - name: Run multiple commands 
        run: |
              echo "Hello famx"
              echo "I'm DevOps Engineer"
  
  job2: 
      name: Testing script workflow
      needs: job1
      runs-on: windows-latest
      steps:
        - name: system information checks
          run: |
                uname -s
                uname -a 
                uname -n
                hostname
  
  job3:
      name: Continous integration and delivery
      needs: [job1,job2]
      runs-on: ubuntu-latest
      steps:
        - name: Checking file systems
          run: |
            echo "I am a mathematician"
            echo $(pwd)
          
        

